language: r
cache: packages
warnings_are_errors: false
dist: trusty

r_packages:
  - Rcpp
  - RcppArmadillo
  - data.table
  - testthat
  - covr

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9


before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"

after_success:
  - Rscript -e 'library(covr); codecov()'
