// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Rcpp_SUTRAS
arma::mat Rcpp_SUTRAS();
RcppExport SEXP _riot_Rcpp_SUTRAS() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(Rcpp_SUTRAS());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_riot_Rcpp_SUTRAS", (DL_FUNC) &_riot_Rcpp_SUTRAS, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_riot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
