# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sinvc <- function(x) {
    .Call('_riot_sinvc', PACKAGE = 'riot', x)
}

sinvr <- function(x) {
    .Call('_riot_sinvr', PACKAGE = 'riot', x)
}

Rcpp_doGRAS <- function(A, u, v, epsilon = 1e-10, maxiter = 1000L, verbose = TRUE) {
    .Call('_riot_Rcpp_doGRAS', PACKAGE = 'riot', A, u, v, epsilon, maxiter, verbose)
}

