# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Leading NA
#'
#' This function returns a logical vector identifying if
#' there are leading NA, marking the leadings NA as TRUE and
#' everything else as FALSE.
#'
#' @param x An integer vector
#' @export
Rcpp_SUTRAS <- function() {
    .Call('_riot_Rcpp_SUTRAS', PACKAGE = 'riot')
}

